spring:
  application:
    name: fantastic
  redis:
    database: 0
    host: 192.168.10.100
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

redisson:
  address: redis://10.18.75.115:6379
  password: 123456