auth-server: http://localhost:8080 # 认证服务器地址

server:
  port: 8085
spring:
  application:
    name: auth-client
security:
  oauth2:
    client:
      client-id: testclient
      client-secret: testclient
      scope: test
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token