auth-server: http://localhost:8080

server:
  port: 8085
spring:
  application:
    name: auth-client
security:
  oauth2:
    client:
      client-id: softmax
      client-secret: 123456
      scope: softmax1
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token