spring:
  application:
    name: spring-tutorial
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.100:3306/spring?useSSL=false
      username: test
      password: 123456
    read:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.100:3306/common?useSSL=false
      username: test
      password: 123456

