spring:
  application:
    name: spring-tutorial
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.10.100:3306/spring?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: test
      password: 123456
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.10.100:3306/common?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: test
      password: 123456
  redis:
    database: 1
    host: 192.168.10.100
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 10
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 10000
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    timeout: 30000

server:
  port: 7001
