spring:
  application:
    name: spring-tutorial
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.10.100:3306/spring?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: test
      password: 123456
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.10.100:3306/common?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: test
      password: 123456

server:
  port: 7001
