spring:
  application:
    name: rocketMQ-tutorial

rocketmq:
  producer:
    # mq的name server地址
    namesrvAddr: 192.168.10.103:9876
    # 客户端验证，允许发送的最大消息体大小 ， 默认 1024*1024*4 (4M)
    maxMessageSize: 131072
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 10000
    # 同步发送失败的话，rocketmq内部重试多少次 ，默认2
    retryTimesWhenSendFailed: 10
    # 异步发送失败的话，rocketmq内部重试多少次 ，默认2
    retryTimesWhenSendAsyncFailed: 10
  consumer:
    namesrvAddr: 192.168.10.103:9876
    # 一次最大消费多少数量消息
    consumerBatchMaxSize: 1
    # 消费线程池的core size
    consumeThreadMin: 20
    # 消费线程池的max size
    consumeThreadMax: 64
    consumerBroadcasting: false
    # 启动的时候是否消费历史记录
    enableHisConsumer: false
    # 启动顺序消费
    enableOrderConsumer: false
    topics:
      -
        topic: user
        tag: usr
      -
        topic: order
        tag: ord
